# Add your LinkedIn email ID and password. WARNING: KEEP THIS OFFLINE ON YOUR PC AND DO NOT COMMIT/UPLOAD.
email: chenshangyicsy@gmail.com
password: Csy2000chen!

# Anti-lock default is False to prevent your PC from sleeping to allow bot to run uninterrupted.
# Set it to True if you wish to disable this functionality.
disableAntiLock: False

# Set to True if you wish to search for remote jobs only.
remote: False

# Set to True if you wish to search for jobs marked as "under 10 applicants" (default is False).
lessthanTenApplicants: False

# Set to True or False to suit your preference. Multiple True allowed.
experienceLevel:
 internship: True
 Entry Level: True
 Associate: True
 mid-senior level: False
 director: False
 executive: False

# Set to True or False to suit your preference. Multiple True allowed.
jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: False
 volunteer: False

# Set ONLY one as True to suit your preference.
date:
 all time: True
 month: False
 week: False
 24 hours: False

# Remove hash sign to add positions. You can add as many as you need, but preserve formatting
positions:
  - Software Engineer
  - Web Developer
  - Flutter
 #- First position
 #- A second position
 #- A third position
 #- ...

# Remove hash sign to add locations. You can add as many as you need including adding 'Remote' as a location but first location must be a valid country.
locations:
  - United States
 #- First location
 #- A second location
 #- A third location
 #- ...
 #- Remote

# Set to True if you are residing in the country of job
residentStatus: True

# Distance from the location added above. Allowed values are {0, 5, 10, 25, 50, 100}, use only one.
distance: 100

# Optional directory to save logs, does not work sometimes. Does not work sometimes, so leave it unchanged.
outputFileDirectory: C:\Users\hecto\Desktop\projects\easyapply\outputs

# Companies you don't want to apply.
companyBlacklist:
 #- company
 #- company2

# Job titles you want to avoid applying. Use it to refine performance of bot.
titleBlacklist:
 #- word1
 #- word2

# Bot will not apply to jobs posted by black listed people.
posterBlacklist:
 #- name1
 #- name2

# Path to your CV/resume and cover letter (remove hash sign). These paths often don't work
# so apply one job manually once, bot will reuse manually uploaded CV for automating the task.
# Note: Prefer a path without spaces, i.e. instead of "Me My" to "MeMy" or "Me_My".
uploads:
 resume: C:\Users\hecto\Desktop\resume\flutter_resume.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # Do you have necessary licenses or certifications required in your profession? E.g. CPA, CA, CFA, professional license
 certifiedProfessional: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting or work on-site to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Do you have security clearance of [xxx] country? (yes/no checkbox)
 securityClearance: False
 # Have you completed the following level of education: DEGREE TYPE? Remove applicable # signs (yes/no checkbox)
 degreeCompleted:
  # - High School Diploma
  # - Bachelor's Degree
  # - Associate's Degree
  - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: universityGpa ---------------
universityGpa: 3.0

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 35000

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # Allowed choices { None, Conversational, Professional, Native or bilingual }
 # arabic:
 # french:

# ------------ Additional parameters: noticePeriod in weeks ---------------
noticePeriod: 8

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
# You may add more skills depending on your industry or profession at the bottom.
experience:
 # normal ones
 Accounting/Auditing: 3
 Administrative : 3
 Advertising : 3
 Analyst : 3
 Art/Creative: 3
 Business Development: 3
 Consulting: 3
 Customer Service: 3
 Distribution Design: 3
 Education: 3
 Engineering: 3
 Finance: 3
 General Business: 3
 Health Care Provider: 3
 Human Resources: 3
 Information Technology: 3
 Legal: 3
 Management: 3
 Manufacturing: 3
 Marketing: 3
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 0
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 VBA: 0
 PowerBI: 0
 PowerQuery: 0
 Excel: 0
 PowerPoint: 0
 Word: 0
 SQL Server: 3
 Communication: 0
 Financial markets: 0
 Business: 3
 Financial services: 0
 Team leadership: 3
 Cash flow: 3
 Hedging: 3
 Treasury services: 3
 Microsoft Power BI: 3
 Accounting: 3
 Auditing: 3
 Financial modeling: 3
 Budgeting & forecasting: 3
 FP&A: 3
 PQE: 3
 Training & Development: 3
 python: 5
 selenium: 3
 # default to put for any industry/skill that you did not list
 default: 3

# ------------ Additional parameters: personal info ---------------
personalInfo:
 Pronouns: Mr.
 First Name: Shangyi
 Last Name: Chen
 Phone Country Code: United States (+1) # See Linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 4697340164
 Street address: 7650 McCallum Blvd, Dallas, TX 75252
 City: Dallas # Include the state/province as well!
 State: Texas
 Zip: 75252
 Linkedin: https://www.linkedin.com/in/shangyi-chen-230291206/
 Website: https://shawnchen-portfolio2024.web.app/ # github/website is interchangeable here
 MessageToManager: "Hi, I am interested to join your organization. Please have a look at my resume. Thank you." # Keep message short and within the quotes. This is a testing feature and may not work.

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Male
 race: Asian
 veteran: None
 disability: None
 citizenship: yes
 clearance: no
